webex/components

- src/adapters/PeopleAdapter.js
- src/adapters/PeopleJSONAdapter.js
- src/adapters/PeopleJSONAdapter.test.js
- src/adapters/WebexAdapter.js
- src/adapters/WebexAdapter.test.js
- src/data/person.json
Adds the ability to pass the json object to the adapter to populate data instead of being hard-coded.
> feat(PeopleJSONAdapter): init with json data

- package.json
Moving this out of the other PR so discussion can focus on one topic at a time 😃
Previous discussion between myself and @lalli-flores
> build(commitlint): allow pascal case scopes for classes

- .eslintrc
- src/components/hooks/usePerson.js
Also fixed the eslint rules order for readability.
> Add ESLint react hooks rules

- src/components/WebexActivity/WebexActivity.stories.js
- src/components/WebexActivity/WebexActivity.test.js
- src/components/WebexActivity/__snapshots__/WebexActivity.test.js.snap
- src/components/WebexActivityStream/WebexActivityStream.stories.js
- src/components/WebexActivityStream/WebexActivityStream.test.js
- src/components/WebexAvatar/WebexAvatar.stories.js
- src/components/WebexAvatar/WebexAvatar.test.js
- src/components/hooks/__mocks__/useActivity.js
- src/components/hooks/__mocks__/usePerson.js
- src/components/hooks/__mocks__/useRoom.js
- src/data/activities.json
- src/data/people.json
- src/data/rooms.json
I moved all the mock object to our data modules. for two reasons:
1 - reusability - Activity Stream mock object will need Activity mock objects which needs Avatar mock objects.
2 -better readability
> Refactor Data and Tests

- src/adapters/RoomsAdapter.js
- src/adapters/RoomsJSONAdapter.test.js
- src/components/WebexActivityStream/WebexActivityStream.js
- src/components/WebexActivityStream/WebexActivityStream.scss
- src/components/WebexActivityStream/WebexActivityStream.stories.js
- src/components/WebexActivityStream/WebexActivityStream.test.js
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.test.js.snap
- src/components/hooks/__mocks__/useActivity.js
- src/components/hooks/__mocks__/useActivityStream.js
- src/components/hooks/__mocks__/usePerson.js
- src/components/hooks/__mocks__/useRoom.js
- src/data/rooms.json
> Time ruler support

- src/components/WebexActivity/README.md
- src/components/WebexActivityStream/README.md
- src/components/WebexAvatar/README.md
- src/components/WebexDataProvider/README.md
- src/components/WebexDataProvider/WebexDataProvider.test.js
- src/components/WebexDataProvider/__snapshots__/WebexDataProvider.test.js.snap
- src/components/hooks/index.js
- src/components/hooks/useActivity.js
- src/components/hooks/useActivityStream.js
- src/components/hooks/usePerson.js
- src/components/hooks/useRoom.js
Pulled out README + adapter refactor on its own PR, outside the component refactor.
> Readme refactor

- src/adapters/ActivitiesJSONAdapter.js
- src/adapters/PeopleJSONAdapter.js
- src/adapters/RoomsAdapter.js
- src/adapters/RoomsAdapter.test.js
- src/adapters/RoomsJSONAdapter.js
- src/adapters/RoomsJSONAdapter.test.js
- src/components/WebexActivity/WebexActivity.scss
- src/components/WebexActivityStream/WebexActivityStream.js
- src/components/WebexActivityStream/WebexActivityStream.scss
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.test.js.snap
- src/components/hooks/__mocks__/useActivityScroll.js
- src/components/hooks/__mocks__/useActivityStream.js
- src/components/hooks/__mocks__/useOverflowActivities.js
- src/components/hooks/index.js
- src/components/hooks/useActivityScroll.js
- src/components/hooks/useActivityStream.js
- src/components/hooks/useOverflowActivities.js
- src/data/rooms.json
Tested with "Hellen Keller" data:
https://github.com/lalli-flores/components/tree/hellen-keller
I would prefer to have this tested with different data set.
> Activity stream loads previous activities of a room

- .storybook/setupTests.js
- __mocks__/date-fns.js
- package-lock.json
- package.json
- src/components/WebexActivity/ActivityHeader.js
- src/components/WebexActivity/ActivityHeader.scss
- src/components/WebexActivity/ActivityHeader.test.js
- src/components/WebexActivity/WebexActivity.js
- src/components/WebexActivity/WebexActivity.scss
- src/components/WebexActivity/WebexActivity.test.js
- src/components/WebexActivity/__snapshots__/ActivityHeader.test.js.snap
- src/components/WebexActivity/__snapshots__/WebexActivity.test.js.snap
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.test.js.snap
Moved `ActivityHeader` into its own component files, outside of `WebexActivity`.
Additionally, fixed date mocking in unit tests.
> Webex Activity component refactor

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/data/meetings.json
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-100969
> feat(MeetingsJsonAdapter): implement getMeeting

- .eslintrc
- .storybook/setupTests.js
- jest-global-setup.js
- package.json
- src/components/WebexMeetingInfo/WebexMeetingInfo.js
- src/components/WebexMeetingInfo/WebexMeetingInfo.scss
- src/components/WebexMeetingInfo/WebexMeetingInfo.stories.js
- src/components/WebexMeetingInfo/WebexMeetingInfo.test.js
- src/components/WebexMeetingInfo/__snapshots__/WebexMeetingInfo.test.js.snap
- src/components/index.js
- src/data/meetings.json
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-101129
> Meeting info component

- package-lock.json
- package.json
- rollup.config.js
- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/components/WebexLocalMedia/WebexLocalMedia.js
- src/components/WebexLocalMedia/WebexLocalMedia.scss
- src/components/WebexLocalMedia/WebexLocalMedia.stories.js
- src/components/WebexLocalMedia/WebexLocalMedia.test.js
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.test.js.snap
- src/components/hooks/__mocks__/useVideo.js
- src/components/hooks/index.js
- src/components/hooks/useVideo.js
- src/components/index.js
- src/data/meetings.json
> Webex Local Media Component

- package-lock.json
- package.json
- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
`addLocalMedia()` is no longer part of the interface.
> Remove add local media

- README.md
- package-lock.json
- package.json
Changes are for development purposes, therefore commit type is `build` to avoid triggering a release.
> Add RxJS as Dev Dependency

- package-lock.json
- package.json
- src/components/WebexAvatar/WebexAvatar.js
- src/components/WebexAvatar/__snapshots__/WebexAvatar.test.js.snap
- src/components/WebexMeetingControl/WebexMeetingControl.js
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.test.js.snap
Commit type for Momentum UI is of type `fix` because this is a fixing change that needs to be released
> Momentum Icon compatibility fix

- src/components/WebexRemoteMedia/WebexRemoteMedia.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
- src/components/WebexRemoteMedia/WebexRemoteMedia.stories.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.test.js
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.test.js.snap
- src/components/hooks/useMeeting.js
- src/data/meetings.json
The scope of the changes in this pull request is around adding the error state to the WebexRemoteMedia component.
[JIRA ticket](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-125735)
Screenshot:
> feat(WebexRemoteMedia): add error state

- src/adapters/MeetingsJSONAdapter.js
- src/components/WebexMeeting/WebexMeeting.js
- src/components/WebexMeeting/WebexMeeting.stories.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.test.js.snap
- src/components/WebexMeetingControl/WebexMeetingControl.stories.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
- src/components/WebexRemoteMedia/WebexRemoteMedia.test.js
- src/components/hooks/useMeeting.js
- src/components/hooks/useStream.js
To add screen share meeting control, remote sharing video in the WebexRemoteMedia, related json adapter and stories.
> feat(WebexMeetingSharing): add screen share meeting control and stories

- package-lock.json
- package.json
- src/components/WebexParticipantRoster/__snapshots__/WebexParticipantRoster.test.js.snap
bump up the version of momentum-ui
> fix(packages): update momentum-ui

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/index.umd.js
- src/styles/index.scss
- src/styles/mixins.scss
- src/styles/momentum-ui.scss
- src/styles/variables.scss
Changes include:
- Updating configuration to produce UMD and minified bundles
- Moving Momentum UI as a dev dependency for ESM modules (pending UMD module on the basis on Momentum UI offering one)
- Added visual analysis of bundles
> Build updates

- .github/ISSUE_TEMPLATE/----bug-report.md
- .github/ISSUE_TEMPLATE/----support--help-.md
- .github/ISSUE_TEMPLATE/---documentation.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/ISSUE_TEMPLATE/config.yml
Create issue templates to help guide developer with questions.
> docs: add Github issue templates

- .storybook/setupTests.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/WebexRemoteMedia/WebexRemoteMedia.stories.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.test.js
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.test.js.snap
- src/components/hooks/__mocks__/useMemberships.js
- src/data/meetings.json
- src/data/memberships.json
The front end portion of the https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-136654 ticket.
> feat(RemoteMedia): add waiting state

- dependencies.md
- package-lock.json
- package.json
Seems I can't get it right 🤦🏻‍♀️
> Add Back Storybook Links Add-on

- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexInMeeting/WebexInMeeting.stories.js
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
- src/styles/_mixins.scss
- src/styles/_variables.scss
PR includes:
* Webex Interstitial
** Has a minimum height that fits the avatar when video is disabled so it doesn't look collapsed
** Expands video to take Webex Interstitial's parent element full size
* Webex In-Meeting
** Handles mobile device styling
> Meeting Component Style Fixes

- .circleci/config.yml
- .nvmrc
Also includes Node.js update to Fermium
> Update CI workflow to build Storybook after release

- README.md
- rollup.config.js
- src/components/WebexActivity/WebexActivity.scss
- src/components/WebexActivityStream/Greeting.scss
- src/styles/_variables.scss
- src/styles/momentum-ui.scss
Adding Momentum UI style instructions as it's causing confusion to developers and leading to compiling errors down the line in consumer's application.
> Peer Momentum UI Styles Usage Instructions

- src/adapters/MembershipJSONAdapter.test.js
- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMember/WebexMember.scss
- src/components/WebexMember/WebexMember.stories.js
- src/components/WebexMember/__snapshots__/WebexMember.stories.storyshot
- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/data/memberships.js
Please give us a feedback for all the changes we added or an overall feedback
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-154242
> feat(WebexMember): display icon when member is muted

- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/components/WebexMemberRoster/WebexMemberRoster.scss
- src/components/WebexMemberRoster/WebexMemberRoster.stories.js
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/_components.scss
- src/data/memberships.js
https://user-images.githubusercontent.com/8277264/110772174-0066a700-8264-11eb-9902-e15f644eda4c.mov
> feat(MemberRoster): show in meeting and not in meeting members

- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/components/WebexMemberRoster/WebexMemberRoster.scss
- src/components/WebexMemberRoster/WebexMemberRoster.stories.js
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/data/memberships.js
- src/data/people.js
- src/styles/_variables.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220414
https://user-images.githubusercontent.com/8277264/112623466-1021e600-8e35-11eb-8324-8397677e7733.mov
> feat(WebexMemberRoster): show warning if member from different org exists

- package-lock.json
- package.json
- src/adapters/OrganizationsJSONAdapter.js
- src/adapters/OrganizationsJSONAdapter.test.js
- src/data/index.js
- src/data/organizations.js
Implement of OrganizationsJSONAdapter as per OrganizationsAdapter interface, create tests for OrganizationsJSONAdapter and create mock data for organizations.
https://jira-eng-gpk2.cisco.com/jira/secure/RapidBoard.jspa?rapidView=6063&view=detail&selectedIssue=SPARK-220422
> feat(OrganizationsJsonAdapter): implement the organizationsJSONAdapter

- src/adapters/MembershipJSONAdapter.js
- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/data/memberships.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222996
> refactor(WebexMember): rename property 'personID' to 'id'

- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMember/WebexMember.scss
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/data/memberships.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220758
https://user-images.githubusercontent.com/8277264/112468341-ccfe3f00-8d70-11eb-970d-c09da8e3d3ff.mov
> feat(WebexMember): indicate current user if in meeting

- src/components/WebexMeeting/README.md
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.stories.js
Update meeting component to use meetingID instead of meetingDestination
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223897
> feat(WebexMeeting): set meetingID as component prop

- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMember/WebexMember.scss
- src/components/WebexMember/WebexMember.stories.js
- src/components/WebexMember/__snapshots__/WebexMember.stories.storyshot
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/data/memberships.js
Display if user is guest in meeting. Updated WebexMember component.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222985
> feat(WebexMember): display if user is guest

- src/components/hoc/withMeeting.jsx
- src/components/index.js
Create a new withMeeting Higher Order Component, for class components
Link sub-task Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224406
> feat(hoc): add a withMeeting HOC for class components

- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexLocalMedia/README.md
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/WebexLocalMedia/WebexLocalMedia.stories.js
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.stories.storyshot
- src/styles/_mixins.scss
When the user is sharing the screen the self-view is replaced by the screen share
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-224481
> feat(WebexLocalMedia): replace self-view with local share

- .eslintrc.json
- package.json
- src/components/WebexActivity/ActivityHeader.jsx
- src/components/WebexActivity/WebexActivity.jsx
- src/components/WebexActivityStream/Greeting.jsx
- src/components/WebexActivityStream/TimeRuler.jsx
- src/components/WebexActivityStream/WebexActivityStream.jsx
- src/components/WebexAvatar/WebexAvatar.jsx
- src/components/WebexDataProvider/WebexDataProvider.jsx
- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/WebexMeetingControls.jsx
- src/components/WebexMeetingInfo/WebexMeetingInfo.jsx
- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/hoc/withMeeting.jsx
Updates ESLint settings so that JSX files are also linted.
> JSX Linter Fixes

- src/adapters/WebexJSONAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-229322
This PR is about adding the connect() and disconnect() functions in the WebexJSONAdapter
> feat(WebexJsonAdapter): add connect() and disconnect() functions

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/hooks/useMeeting.js
- src/data/meetings.js
Implement meeting state in MeetingJsonAdapter and WebexMeeting component, update tests and meeting mock data
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223894
> feat(WebexMeeting): implement meeting state

- src/components/hooks/useMeeting.js
- src/components/hooks/useMeetingDestination.js
Remove the state detection from the meeting hooks
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223895
> refactor(WebexMeeting): remove the state detection from the meeting hooks

- src/adapters/WebexJSONAdapter.js
refactor(WebexJsonAdapter): extend all JSON adapter classes from interfaces
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-232566
> refactor(WebexJsonAdapter): extend all json adapter classes from interfaces

- src/adapters/MeetingsJSONAdapter.js
- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/WebexMediaAccess.scss
- src/components/WebexMediaAccess/WebexMediaAccess.stories.js
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
- src/components/_components.scss
Create Media Access component and add Camera story
> feat(WebexMediaAccess): add media access component

- package-lock.json
- package.json
This PR is about updating the component-adapter-interfaces version
> fix(package): update component adapter interfaces to v1.17.0

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMember/WebexMember.stories.js
- src/components/hooks/useOrganization.js
- src/data/memberships.js
- src/storyshots.test.js
This PR is about fixing the unit tests warnings
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-236058
> fix(components): fix test warnings

- src/adapters/MeetingsJSONAdapter.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/data/meetings.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-235304
> feat(MeetingsJsonAdapter): add settings control

- src/adapters/MeetingsJSONAdapter.js
- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/WebexMediaAccess.stories.js
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
Add Media (microphone) Access component and add Microphone story
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-234476
> feat(WebexMediaAccess): add microphone access screen

- src/components/WebexMember/WebexMember.stories.js
- src/components/hoc/withAdapter.jsx
- src/components/hoc/withAdapter.test.jsx
- src/components/hooks/useOrganization.js
- src/components/index.js
- src/data/memberships.js
- src/storyshots.test.js
This PR is about fixing the unit tests warnings
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-236058
> fix(Components): fix tests warnings

- src/components/WebexSettings/Tabs.jsx
- src/components/WebexSettings/Tabs.scss
- src/components/WebexSettings/WebexSettings.jsx
- src/components/WebexSettings/WebexSettings.scss
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/_components.scss
Create a tabs component to be used in the settings component.
Render the tab content only when the corresponding tab is selected.
> feat(WebexComponents): add Tabs component

- src/components/_components.scss
- src/components/generic/Modal/Modal.jsx
- src/components/generic/Modal/Modal.scss
- src/components/generic/index.scss
- src/components/index.js
This PR is about implementing the Modal component
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-241415
> feat(Modal): add Modal component

- src/components/WebexSettings/Select.jsx
- src/components/WebexSettings/Tabs.jsx
This PR is about fixing the test warnings for Tabs and Select components
> fix(WebexSettings): fix JSDoc warnings for Tabs and Select components

- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/components/WebexMeeting/WebexMeeting.stories.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/WebexMeetingControl.stories.js
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/hooks/useMeetingControl.js
Still to be done:  add a story in WebexMeetingControl's storybook
> feat(WebexMeetingControl): render dropdown controls

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/index.js
- src/data/meetings.js
Create a selection control with additional properties options and selected.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-240363
Depends on: #254
> feat(MeetingsJsonAdapter): add microphone selection control

- src/components/WebexMember/WebexMember.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-244333
> fix(WebexMember): use displayName instead of firstName and lastName

- src/components/WebexMeeting/WebexMeeting.jsx
This PR is about display the WebexSettings component in a closable modal
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-235312
> feat(WebexMeeting): display webex settings in a modal window

- src/components/WebexMicrophoneSettings/WebexMicrophoneSettings.jsx
- src/components/WebexMicrophoneSettings/WebexMicrophoneSettings.scss
- src/components/WebexMicrophoneSettings/WebexMicrophoneSettings.stories.js
- src/components/WebexMicrophoneSettings/__snapshots__/WebexMicrophoneSettings.stories.storyshot
- src/components/WebexSettings/WebexSettings.jsx
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/_components.scss
List a dropdown for all available microphones.
Depends on https://github.com/webex/components/pull/258 and https://github.com/webex/components/pull/251
Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-237275
> feat(WebexMicrophoneSettings): show all available microphones in a dropdown

- src/components/WebexSettings/WebexSettings.jsx
- src/components/WebexSettings/WebexSettings.stories.js
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/WebexVideoSettings/WebexVideoSettings.jsx
- src/components/WebexVideoSettings/WebexVideoSettings.scss
- src/components/WebexVideoSettings/__snapshots__/WebexVideoSettings.stories.storyshot
- src/components/_components.scss
List a dropdown for all available cameras
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-235908
> feat(WebexVideoSettings): show all available cameras in a dropdown

- package.json
update React and React-DOM version to v17.0.2
> build(package): upgrade react version from 16.13.1 to 17.0.2

- src/components/hooks/useMeetingControl.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-245967
> fix(WebexMeetingControl): render the control when an existent type is entered after a non-existent

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchSpeakerControl.js
- src/adapters/MeetingsJSONAdapter/controls/index.js
- src/data/meetings.js
Create speaker selection control
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-240807
Depends on: #254
> feat(MeetingsJsonAdapter): add speaker selection control

- src/components/WebexAudioSettings/WebexAudioSettings.jsx
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
List a dropdown for all available speakers.
Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-243702
> feat(WebexAudioSettings): add switch-speaker control in the settings page

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/MuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteVideoControl.js
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/hooks/useMeeting.js
- src/components/hooks/useMeetingDestination.js
- src/data/meetings.js
- src/util.js
Transform localAudio and localVideo properties into objects with "stream" and "permission" properties inside.  
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-247393
> fix(WebexMeeting): transform localAudio and localVideo into objects

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/ShareControl.js
- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/data/meetings.js
Transform localShare property into an object containing "stream" property.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-249801
> feat(MeetingsJsonAdapter): transform localShare into an object

- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchMicrophoneControl.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-250693
> fix(controls): call distinctUntilChanged without a string parameter

- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchSpeakerControl.js
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
Disable dropdown and add no-devices control when there are no devices
> feat(dropdown-controls): disable control when there are no media devices available

- src/components/hooks/useMeetingDestination.js
Update useMeetingDetination hook to leave the meeting when the browser tab is closed.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-247837
> feat(UseMeetingDestination): leave meeting when browser tab is closed

- src/components/hooks/useStream.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251735
> fix(UseStream): make hook ignore uninitialized react ref

- src/components/hooks/useSpeakers.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251572
> fix(UseSpeakers): make hook ignore uninitialized react ref

- src/components/hooks/useMeetingDestination.js
- src/util.js
Chain dependent observables createMeeting and getMeeting
> fix(UseMeetingDestination): chain createMeeting with getMeeting

- src/components/hooks/useStream.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251735
> fix(UseStream): update the hook to ignore uninitialized react ref

- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMember/__snapshots__/WebexMember.stories.storyshot
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/data/people.js
Display the domain name for member's email if organization can't be loaded
> feat(WebexMember): display member's email domain if organization is not accessible

- src/components/WebexMeeting/WebexMeeting.scss
- src/styles/index.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254203
> feat(WebexMeeting): theme infrastructure

- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/helpers.js
Fix for missing classname prefix
> fix(WebexComponentClasses): add support for prefixed optional css classes

- src/adapters/MeetingsJSONAdapter/controls/MuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteVideoControl.js
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/WebexMeetingControl.scss
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
- src/components/_components.scss
- src/components/hooks/useElementDimensions.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-252931
> feat(WebexMeetingControl): display text on control buttons

- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/RosterControl.js
- src/adapters/MeetingsJSONAdapter/controls/SettingsControl.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-256359
> fix(MeetingControls): remove text from roster and settings controls

- src/styles/_mixins.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254209
> feat(WebexLocalMedia): move small media window in bottom right corner

- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingInfo/WebexMeetingInfo.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
Style the component as per theme design.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254207
> feat(WebexMeetingInfo): theme meeting info component

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.scss
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.scss
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
When controls width is bigger than its container the text should be hidden otherwise this should be shown.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-257320
> feat(WebexMeetingControlsBar): show/hide buttons text depending on controls width

- src/components/WebexMeeting/WebexMeeting.scss
- src/styles/_colors.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254217
> feat(WebexMeeting): theme the Webex meeting component

- src/components/hooks/useMeeting.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-258294
> fix(UseMeeting): use meetingsAdapter only if adapter is defined

- src/components/generic/Modal/Modal.jsx
- src/components/generic/Modal/Modal.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
Replace momentumUI modal component with a custom component
> feat(Modal): create modal component

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.stories.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-258312
> feat(WebexMeeting): accept empty meeting id and add corresponding story in storybook

- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/WebexLocalMedia/WebexLocalMedia.scss
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/generic/Banner/Banner.jsx
- src/components/generic/Banner/Banner.scss
- src/components/generic/_generic.scss
- src/styles/_colors.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
Add a "My preview" banner to the local media component, in the interstitial meeting. The banner should only be present on the "big" video, and only when the local video is available. 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254211
> feat(WebexComponents): add "My preview" banner 

- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/JoinControl.js
- src/adapters/MeetingsJSONAdapter/controls/LeaveControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteVideoControl.js
- src/adapters/MeetingsJSONAdapter/controls/ProceedWithoutCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/ProceedWithoutMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/RosterControl.js
- src/adapters/MeetingsJSONAdapter/controls/SettingsControl.js
- src/adapters/MeetingsJSONAdapter/controls/ShareControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchSpeakerControl.js
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-256234
> feat(MeetingControls): add types for meeting controls

- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/generic/Banner/Banner.scss
- src/themes/legacy.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254222
> feat(WebexInMeeting): add background with gradient to share banner

- src/components/generic/Modal/Modal.jsx
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-260267
> feat(Modal): add ghost button to the modal

- src/components/generic/Icon/Icon.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-260334
> feat(WebexComponents): get the icon size based on the name of the icon

- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingInfo/WebexMeetingInfo.jsx
- src/components/WebexMeetingInfo/__snapshots__/WebexMeetingInfo.stories.storyshot
- src/components/WebexMember/WebexMember.jsx
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.stories.storyshot
- src/components/generic/Spinner/Spinner.jsx
- src/components/generic/Spinner/Spinner.scss
- src/components/generic/_generic.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-259196
> feat(Spinner): create spinner component

- src/components/WebexMeeting/WebexMeeting.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-261278
> feat(WebexMeeting): add padding to Webex meeting component

- src/adapters/MeetingsJSONAdapter/controls/DisabledJoinControl.js
- src/adapters/MeetingsJSONAdapter/controls/DisabledMuteAudioControl.js
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-259362
> fix(MeetingControls): add types for join and mute audio controls when disabled

- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexVideoSettings/WebexVideoSettings.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-260712
> feat(WebexComponents): make WebexLocalMedia accept a banner prop

- src/components/WebexSettings/Tabs.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-258821
> feat(WebexSettings): tabs as pills

- src/components/generic/Modal/Modal.jsx
- src/components/generic/Modal/Modal.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
Style modal component in mobile view, add breakpoints variables and mixins
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-258323
> feat(Modal): style modal component in mobile view

- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/generic/Icon/Icon.jsx
- src/components/generic/Select/Select.jsx
- src/themes/legacy.scss
This fix is needed because on option change the select do not keep the selected value.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-262248
> fix(Select): select value is not updated on change

- src/components/WebexMeeting/WebexMeeting.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-261739
> feat(WebexMeeting): theme the WebexMeetingControlBar in WebexMeeting

- src/components/WebexMember/__snapshots__/WebexMember.stories.storyshot
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/data/people.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-261741
> fix(people): add an existing organization id for user6

- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexLocalMedia/WebexLocalMedia.scss
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-260359
> feat(WebexRemoteMedia): crop media inside the meeting

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-259888
> feat(WebexComponent): theme the display of roster component on mobile

- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.stories.storyshot
- src/components/generic/Badge/Badge.jsx
- src/components/generic/Badge/Badge.scss
- src/components/generic/_generic.scss
- src/styles/_colors.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
Create themed Badge component, and use in remote video (connected section).
> feat(Badge): create badge component

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254248
> feat(WebexMeeting): show a toast when video or audio mute controls change state

- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.jsx
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.stories.js
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexLocalMedia/WebexLocalMedia.jsx
- src/components/WebexLocalMedia/WebexLocalMedia.scss
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexVideoSettings/WebexVideoSettings.jsx
- src/components/WebexVideoSettings/WebexVideoSettings.scss
- src/components/generic/Banner/Banner.jsx
- src/components/generic/Banner/Banner.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-261624
> feat(WebexComponents): move preview banner on the parent

- jest.setup.js
- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.stories.storyshot
- src/components/WebexAvatar/WebexAvatar.jsx
- src/components/WebexAvatar/WebexAvatar.scss
- src/components/WebexAvatar/WebexAvatar.stories.js
- src/components/WebexAvatar/__snapshots__/WebexAvatar.stories.storyshot
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.stories.storyshot
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.stories.storyshot
- src/components/WebexMember/__snapshots__/WebexMember.stories.storyshot
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/themes/dark.scss
- src/themes/light.scss
PR: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-259899
> feat(WebexAvatar): Add placeholder with random background color and capital letter initials

- src/components/WebexActivity/ActivityHeader.jsx
- src/components/WebexActivity/ActivityHeader.scss
- src/components/WebexActivity/WebexActivity.scss
- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263647
> feat(WebexActivity): theme the WebexActivity component

- src/components/WebexActivityStream/Greeting.jsx
- src/components/WebexActivityStream/Greeting.scss
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263648
> feat(WebexActivityStream): theme the WebexActivityStream component

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
- src/components/generic/Icon/Icon.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-262132
> feat(Icon): map theme "camera on" icon to muted momentum icon

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/generic/Modal/Modal.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-262983
> fix(WebexMeeting): set proper settings modal dimensions

- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/components/WebexMemberRoster/WebexMemberRoster.scss
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/styles/_colors.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-257975
> feat(WebexMemberRoster): theme Webex member roster component

- rollup.config.js
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263964
> feat(WebexMeeting): export loading gif

- src/components/generic/OptionsList/OptionsList.scss
Add border on options list container when is active
> feat(OptionsList): add border on options list container when is active

- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexMeeting/WebexMeeting.scss
- src/themes/dark.scss
- src/themes/legacy.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-254218
> feat(WebexInMeeting): theme the Webex in meeting component

- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/WebexMeetingControl.scss
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/generic/Button/Button.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264013
> fix(WebexMeetingControl): add container element to prevent css rule conflicts

- src/components/WebexAvatar/WebexAvatar.jsx
- src/components/WebexAvatar/WebexAvatar.scss
- src/components/WebexAvatar/__snapshots__/WebexAvatar.stories.storyshot
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263896
> feat(WebexAvatar): add avatar bot status

- src/components/WebexMeeting/WebexMeeting.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264588
> fix(WebexMeeting): set the correct position for the meeting logo

- src/adapters/MeetingsJSONAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264750
> fix(MeetingsJsonAdapter): stop stream on localShare

- src/components/WebexInMeeting/WebexInMeeting.jsx
- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264660
> feat(WebexMeeting): make video occupy only available vertical space

- rollup.config.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-262986
> fix(fonts): add cisco fonts to build folder

- src/adapters/MeetingsJSONAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264709
> fix(MeetingsJsonAdapter): stop stream when switching microphones

- src/components/WebexMeeting/WebexMeeting.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-265495
> fix(WebexMeeting): make dark and light loading logos smaller

- src/adapters/MeetingsJSONAdapter.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-265462
> fix(MeetingsJsonAdapter): show local media before the first interaction with corresponding controls

- src/components/WebexAvatar/WebexAvatar.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-265491
> feat(WebexAvatar): make avatar bigger

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-265492
> feat(WebexMeeting): add margins to the meeting logo

- src/components/WebexInMeeting/WebexInMeeting.scss
- src/themes/dark.scss
- src/themes/light.scss
This PR add a correct background color for in meeting local media depending on the theme. This is visible when the camera is turned off.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-266648
> fix(WebexInMeeting): add background to in meeting local media

- src/components/WebexMediaAccess/WebexMediaAccess.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-267077
> feat(WebexMediaAccess): add background to the mediaAccess component

- .storybook/preview.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-265511
> feat(storybook): make storybook refresh data before each story

- src/components/WebexMeetingInfo/WebexMeetingInfo.jsx
- src/components/WebexMeetingInfo/WebexMeetingInfo.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-266992
> fix(WebexMeetingInfo): add font size values for meeting info depending on the device type

- src/components/generic/OptionsList/OptionsList.jsx
- src/components/generic/OptionsList/OptionsList.scss
- src/components/generic/Select/Select.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-267148
> fix(OptionsList): show "selected" icon in its own column

- src/components/WebexMember/WebexMember.scss
Updates roster guest font color so it is complaint with contrast accessibility requirements
> fix(WebexMember): set higher font color contrast for "guest" role

- src/components/WebexMeeting/WebexMeeting.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-267914
> fix(WebexMeeting): resize dark and light loading logos

- src/components/WebexAudioSettings/WebexAudioSettings.jsx
In this task has been implemented the case if a user does not have microphone or audio permission, then an on-screen error will be received in the Audio Settings area.
Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-268155
> feat(WebexAudioSettings): displays the error when no microphone is avail

- src/components/WebexSettings/Tabs.scss
- src/themes/dark.scss
- src/themes/light.scss
Add missing states(hover and active) on tabs.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-267923
> fix(WebexSettings): add missing states on tabs

- src/components/generic/Icon/Icon.jsx
- src/components/icons/AudioMicrophoneIcon.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-269354
> fix(icons): remove indicator prop from icons because it is not used anywhere

- src/components/generic/Icon/Icon.jsx
- src/components/icons/ArrowLeft.jsx
- src/components/icons/index.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-271378
> feat(Icons): add "arrow-left" icon

- src/components/WebexMeetingAuthentication/WebexMeetingAuthentication.jsx
- src/components/WebexMeetingAuthentication/WebexMeetingAuthentication.scss
- src/components/_components.scss
- src/components/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-271787
> feat(WebexMeetingAuthentication): create WebexMeetingAuthentication component

- src/components/generic/Select/Select.scss
- src/themes/dark.scss
- src/themes/light.scss
PR for: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-271751
Dropdown style changes.
> fix(Select): change dropdown fields style in the Settings window

- src/components/generic/InputField/InputField.jsx
- src/components/generic/InputField/InputField.scss
- src/components/generic/_generic.scss
- src/styles/_colors.scss
- src/themes/dark.scss
- src/themes/light.scss
Create and style input field component.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-270413
> feat(InputField): create and style input field component

- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279631
> fix(WebexMeetingHostAuthentication): add space between the spinner and the text on the button

- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/DisabledMuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/LeaveControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteVideoControl.js
- src/adapters/MeetingsJSONAdapter/controls/SettingsControl.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMemberRoster/WebexMemberRoster.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-278998
> feat(webex-meeting-controls): remove size from icon names

- src/adapters/MeetingsJSONAdapter.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279687
> fix(MeetingsJsonAdapter): toggleMuteAudio and toggleMuteVideo return structure

- src/components/generic/InputField/InputField.scss
- src/styles/_colors.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-280350
> fix(InputField): change the font size and the colors of shadow and border

- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-280757
> fix(WebexMeetingHostAuthentication): add margin and line-height to label text

- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.scss
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.scss
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279555
> feat(WebexMeetingAuthentication): change the title font size in mobile viewport

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexWaitingForHost/WebexWaitingForHost.jsx
- src/components/WebexWaitingForHost/WebexWaitingForHost.scss
- src/components/WebexWaitingForHost/__snapshots__/WebexWaitingForHost.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-279567
> fix(WebexWaitingForHost): add 'Cancel' button to WebexWaitingForHost component

- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/generic/InputField/InputField.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281188
> feat(WebexMeetingAuthentication): add aria-label on all elements from authentication components

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281659
> feat(WebexMeetingControlBar): add tabindex to collapse button

- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281671
> fix(WebexMeetingControlBar): add setTimeout before eventListener

- src/adapters/MeetingsJSONAdapter.js
- src/components/generic/Select/Select.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-280505
> fix(WebexComponents): switch camera/microphone/speakers in WebexSettings

- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281886
> feat(WebexMeetingAuthentication): auto focus the first control

- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/generic/InputField/InputField.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281885
> feat(InputField): add 'autoFocus' prop to InputField component

- .eslintrc.json
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/generic/InputField/InputField.jsx
- src/components/generic/Modal/Modal.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281286
> feat(WebexMeetingGuestAuthentication): add custom tab order

- src/components/generic/Modal/Modal.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281241
> feat(Modal): close modal on "esc" keypress

- src/components/WebexMeeting/WebexMeeting.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281275
> feat(WebexMeeting): use 'ariaLabel' prop for settings modal

- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
- src/components/generic/Icon/Icon.jsx
- src/components/icons/CameraBoldIcon.jsx
- src/components/icons/MicrophoneBoldIcon.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281236
> feat(WebexMediaAccess): add aria-label on icon for accessibility

- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/generic/Modal/Modal.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-281288
> feat(WebexMeetingHostAuthentication): add custom tab order

- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/generic/Select/Select.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282311
> feat(Select): toggle/collapse dropdown when pressing enter or space on the keyboard

- package-lock.json
- package.json
https://github.com/webex/components/pull/558
> fix(package): update component adapter interfaces to v1.22.0﻿

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282018
> fix(WebexMeetingControlBar): set meeting controls tab indexes based on collapseStart

- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282398
> feat(WebexMemberRoster): use tabIndex for close button

- src/components/generic/OptionsList/OptionsList.jsx
- src/components/generic/OptionsList/OptionsList.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282835
> refactor(OptionsList): use state for hovered option instead of :hover pseudoclass

- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.scss
- src/components/WebexSettings/Tabs.scss
- src/components/generic/Button/Button.scss
- src/styles/_mixins.scss
- src/themes/dark.scss
- src/themes/light.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282101
> feat(generic-components): add box-shadow to focused elements

- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/generic/OptionsList/OptionsList.jsx
- src/components/generic/Select/Select.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-270613
> feat(OptionsList): implement arrow keys navigation in options-list for accessibility

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-282991
> feat(WebexMeetingGuestAuthentication): add keyUp handler to host link

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283332
> feat(WebexMeetingControlBar): add aria-hidden to meeting controls refs container

- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283396
> fix(WebexMeetingControlBar): move action of collapsed controls from the control to the options list

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexWaitingForHost/WebexWaitingForHost.jsx
- src/components/WebexWaitingForHost/__snapshots__/WebexWaitingForHost.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283358
> fix(WebexWaitingForHost): rename button from "Cancel" to "Leave"

- src/components/generic/OptionsList/OptionsList.jsx
- src/components/generic/Select/Select.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283354
> feat(Select): close the option list on blur

- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283411
> feat(WebexMediaAccess): add tooltips on proceed without camera/audio buttons

- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.scss
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-283628
> fix(WebexMeeting): avoid adding the scrollbar for authentication forms

- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284121
> feat(WebexMediaAccess): add aria-label to 'Proceed without' buttons

- src/components/WebexMemberRoster/WebexMemberRoster.jsx
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
- src/components/generic/Modal/Modal.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284123
> feat(WebexComponents): add aria-label to close buttons

- src/adapters/MeetingsJSONAdapter.js
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/data/meetings.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284115
> feat(MeetingsJsonAdapter): show initial speaker

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexWaitingForHost/WebexWaitingForHost.jsx
- src/components/WebexWaitingForHost/__snapshots__/WebexWaitingForHost.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284124
> feat(WebexWaitingForHost): change label and add aria-label for button

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexWaitingForHost/WebexWaitingForHost.jsx
- src/components/WebexWaitingForHost/__snapshots__/WebexWaitingForHost.stories.storyshot
- src/components/icons/WaitingForHostIcon.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284418
> feat(WebexWaitingForHost): add aria-label on WaitingForHost icon

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchSpeakerControl.js
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/data/meetings.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284115
> feat(MeetingsJsonAdapter): add browser default speaker to the available speaker list

- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/JoinControl.js
- src/adapters/MeetingsJSONAdapter/controls/LeaveControl.js
- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/WebexSettings/Tabs.jsx
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/generic/Modal/Modal.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284360
> feat(WebexComponents): prefix aria label value with button text

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexWaitingForHost/WebexWaitingForHost.jsx
- src/components/WebexWaitingForHost/__snapshots__/WebexWaitingForHost.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285013
> feat(WebexWaitingForHost): add tab index to button

- src/components/generic/OptionsList/OptionsList.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285335
> feat(OptionsList): create the Option component that can be focusable for navigation with arrow keys

- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285457
> fix(WebexMeetingControlBar): set a valid fallback for invalid range value

- src/components/generic/InputField/InputField.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-286159
> fix(InputField): apply correct background for input with an error

- src/components/WebexMeeting/WebexMeeting.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-286516
> feat(WebexMeeting): set min-width for the settings and authentication modal to 18.5 rem

- src/components/WebexSettings/Tabs.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-286724
> fix(WebexSettings): set autofocus on settings modal

- src/components/generic/Tooltip/Tooltip.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289130
> fix(Tooltip): controls tooltips don't hide on mobile devices

- src/components/generic/InputField/InputField.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285598
> feat(InputField): allow show/hide password button to be accessed via keyboard

- src/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/adaptive-cards/AdaptiveCard/AdaptiveCard.scss
- src/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/adaptive-cards/Component/Component.jsx
- src/adaptive-cards/Component/Component.scss
- src/components/_components.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-291270
> feat(AdaptiveCard): create dummy adaptive card component

- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputTime/InputTime.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-291312
> feat(AdaptiveCardsInputTime): create dummy Input.Time component

- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputDate/InputDate.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-291311
> feat(AdaptiveCardsInputDate): create dummy Input.Date component

- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputToggle/InputToggle.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-291331
> feat(AdaptiveCardsInputToggle): create dummy Input.Toggle component

- src/components/WebexSettings/Tabs.jsx
- src/components/WebexSettings/Tabs.scss
- src/components/WebexSettings/WebexSettings.jsx
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285592
> fix(Tabs): change focus on tab instead of container

- src/components/adaptive-cards/Component/Component.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292481
> fix(AdaptiveCardsComponent): move individual component imports at the top of the file

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.scss
- src/components/adaptive-cards/_adaptive-cards.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-291797
> feat(TextBlock): create TextBlock component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputDate/InputDate.jsx
- src/components/adaptive-cards/InputNumber/InputNumber.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/InputTime/InputTime.jsx
- src/components/adaptive-cards/InputToggle/InputToggle.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293197
> feat(AdaptiveCardsComponent): implement registerComponent

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/Column/Column.scss
- src/components/adaptive-cards/_adaptive-cards.scss
- src/components/helpers.js
- src/themes/dark.scss
- src/themes/light.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292473
> feat(Column): create Column component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/Image/Image.scss
- src/components/adaptive-cards/_adaptive-cards.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292445
> feat(Image): create Image component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.scss
- src/components/adaptive-cards/_adaptive-cards.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292440
> feat(ImageSet): create ImageSet component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/Container/Container.scss
- src/components/adaptive-cards/_adaptive-cards.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-291943
> feat(AdaptiveCardsContainer): create Container component

- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292786
> feat(AdaptiveCardsComponent): implement inherited properties 'separator', 'spacing' and 'isVisible'

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292444
> feat(AdaptiveCardsRichTextBlock): create RichTextBlock component

- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
- src/themes/dark.scss
- src/themes/light.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292813
> feat(AdaptiveCardsComponent): implement properties 'color' and 'isSubtle'

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/FactSet/FactSet.jsx
- src/components/adaptive-cards/FactSet/FactSet.scss
- src/components/adaptive-cards/_adaptive-cards.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292442
> feat(AdaptiveCardsFactSet): create FactSet component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/Container/Container.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293854
> feat(AdaptiveCardsComponent): implement 'bleed' property

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292800
> feat(AdaptiveCardsComponent): implement properties 'minHeight', 'height', 'verticalContentAlignment'

- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-294171
> feat(AdaptiveCardsComponent): add default props for adaptive cards

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/helpers.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293883
> feat(AdaptiveCard): make AdaptiveCard use Component

- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292446
> feat(AdaptiveCardsActionSet): create ActionSet component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/Container/Container.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292830
> feat(AdaptiveCardsComponent): implement backgroundImage property

- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/Image/Image.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-295151
> feat(AdaptiveCardsComponent): implement width property

- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/generic/InputField/InputField.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292447
> feat(AdaptiveCardsInputText): implement Input.Text component

- src/components/_components.scss
- src/components/inputs/Textbox/Textbox.jsx
- src/components/inputs/Textbox/Textbox.scss
- src/components/inputs/_inputs.scss
- src/themes/dark.scss
- src/themes/light.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289988
> feat(Textbox): implement Textbox component

- src/components/adaptive-cards/Action/Action.jsx
- src/components/adaptive-cards/Action/Action.scss
- src/components/adaptive-cards/ActionOpenURL/ActionOpenUrl.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/_adaptive-cards.scss
- src/components/generic/Button/Button.jsx
- src/util.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292805
> feat(AdaptiveCardsActionOpenUrl): create Action.OpenUrl component

- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.scss
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.scss
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/generic/InputField/InputField.jsx
- src/components/generic/InputField/InputField.scss
- src/components/generic/Select/Select.jsx
- src/components/generic/Select/Select.scss
- src/components/inputs/Label/Label.jsx
- src/components/inputs/Label/Label.scss
- src/components/inputs/Textbox/Textbox.jsx
- src/components/inputs/Textbox/Textbox.scss
- src/components/inputs/_inputs.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-296620
> feat(inputs): implement Label component

- src/components/inputs/RadioButton/RadioButton.jsx
- src/components/inputs/RadioButton/RadioButton.scss
- src/components/inputs/_inputs.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289976
> feat(RadioButton): create radio button component

- src/components/generic/InputField/InputField.jsx
- src/util.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-298785
> fix(InputField): clamp input value between min and max

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/InputNumber/InputNumber.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/context/adaptive-card-context.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-296963
> feat(AdaptiveCardContext): implement input data management

- src/components/generic/InputField/InputField.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-298770
> fix(InputField): prevent clear button overlapping inserted number

- src/components/adaptive-cards/Action/Action.jsx
- src/components/adaptive-cards/Action/Action.scss
- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/ActionShowCard/ActionShowCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/generic/Button/Button.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292807
> feat(AdaptiveCardsActionShowCard): create Action.ShowCard component

- src/components/WebexAvatar/WebexAvatar.scss
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.scss
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.scss
- src/components/WebexMemberRoster/WebexMemberRoster.scss
- src/components/WebexSettings/Tabs.scss
- src/components/adaptive-cards/Component/Component.scss
- src/components/generic/Button/Button.scss
- src/components/generic/InputField/InputField.scss
- src/components/generic/OptionsList/Option.scss
- src/components/generic/OptionsList/OptionsList.scss
- src/components/generic/Select/Select.scss
- src/components/generic/Spinner/Spinner.scss
- src/components/inputs/Textbox/Textbox.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-273378
> fix(themes): standardize naming of scss variables

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/generic/Select/Select.jsx
- src/components/inputs/RadioButton/RadioButton.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292452
> feat(AdaptiveCardsInputChoiceSet): create InputChoiceSet component

- src/components/adaptive-cards/ActionOpenURL/ActionOpenUrl.jsx
- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/ActionShowCard/ActionShowCard.jsx
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/FactSet/FactSet.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/InputNumber/InputNumber.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292804
> feat(AdaptiveCardsComponent): implement fallback property

- src/components/adaptive-cards/ActionOpenURL/ActionOpenUrl.jsx
- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/ActionToggleVisibility/ActionToggleVisibility.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/FactSet/FactSet.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/adaptive-cards/InputDate/InputDate.jsx
- src/components/adaptive-cards/InputNumber/InputNumber.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/InputTime/InputTime.jsx
- src/components/adaptive-cards/InputToggle/InputToggle.jsx
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292808
> feat(AdaptiveCardsActionToggleVisibility): create Action.ToggleVisibility component

- src/components/generic/Select/Select.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302017
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302022
> fix(Select): modify incorrect values for scss variables

- src/components/hooks/useAdaptiveCard.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-293314
> feat(hooks): implement useAdaptiveCard hook

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/InputTime/InputTime.jsx
- src/components/adaptive-cards/InputTime/InputTime.scss
- src/components/adaptive-cards/_adaptive-cards.scss
- src/util.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292450
> feat(AdaptiveCardsInputTime): implement Input.Time component

- src/components/adaptive-cards/Action/Action.scss
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/Spacer/Spacer.jsx
- src/components/adaptive-cards/Spacer/Spacer.scss
- src/components/adaptive-cards/_adaptive-cards.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-295262
> feat(AdaptiveCard): implement spacing and separator properties

- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/generic/Button/Button.jsx
- src/components/generic/InputField/InputField.jsx
- src/components/generic/OptionsList/Option.jsx
- src/components/generic/OptionsList/OptionsList.jsx
- src/components/generic/Select/Select.jsx
- src/components/inputs/Checkbox/Checkbox.jsx
- src/components/inputs/RadioButton/RadioButton.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302188
> fix(inputs): set default value for tabIndex to zero

- src/components/adaptive-cards/ActionSubmit/ActionSubmit.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputNumber/InputNumber.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/util.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292806
> feat(AdaptiveCardsActionSubmit): create Action.Submit component﻿

- src/components/generic/OptionsList/Option.scss
- src/components/generic/OptionsList/OptionsList.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302198
> fix(Option): change the color of the check icon and remove the border and background from it

- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/generic/Select/Select.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302174
> feat(Select): allow select options to expand horizontally

- src/components/_components.scss
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/inputs/RadioButton/RadioButton.jsx
- src/components/inputs/RadioButton/RadioButton.scss
- src/components/inputs/Toggle/Toggle.jsx
- src/components/inputs/Toggle/Toggle.scss
- src/components/inputs/_inputs.scss
- src/components/inputs/index.js
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289981
> feat(inputs): create Toggle component

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/generic/InputField/InputField.scss
- src/components/inputs/Textbox/Textbox.jsx
- src/components/inputs/Textbox/Textbox.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-301443
> feat(AdaptiveCardsInputText): render Textbox component depending on isMultiline property

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302481
> docs(AdaptiveCard): display submitted values in storybook

- src/components/adaptive-cards/ActionSet/ActionSet.scss
- src/components/adaptive-cards/_adaptive-cards.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302771
> fix(AdaptiveCardsActionSet): add margin bottom to ActionSet

- src/components/generic/Button/Button.jsx
- src/components/generic/InputField/InputField.jsx
- src/components/inputs/Checkbox/Checkbox.jsx
- src/components/inputs/Label/Label.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-301445
> docs(components): explain eslint disabled accessibility rules

- src/components/generic/InputField/InputField.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302133
> fix(InputField): remove focus on the increment controls after click

- src/adapters/ActivitiesJSONAdapter.js
- src/adapters/ActivitiesJSONAdapter.test.js
- src/components/WebexActivity/WebexActivity.stories.js
- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/hooks/index.js
- src/components/hooks/useAdaptiveCard.js
- src/data/activities.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-301448
> feat(ActivitiesJsonAdapter): implement postAction() and use it in useActivity hook

- src/util.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303378
> fix(InputTime): display the missing hours and minutes

- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292824
> feat(AdaptiveCardsComponent): implement inherited verticalContentAlignment property

- src/components/adaptive-cards/Action/Action.jsx
- src/components/adaptive-cards/ActionOpenURL/ActionOpenUrl.jsx
- src/components/adaptive-cards/ActionShowCard/ActionShowCard.jsx
- src/components/adaptive-cards/ActionSubmit/ActionSubmit.jsx
- src/components/adaptive-cards/ActionToggleVisibility/ActionToggleVisibility.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/FactSet/FactSet.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/adaptive-cards/InputDate/InputDate.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/InputTime/InputTime.jsx
- src/components/adaptive-cards/InputToggle/InputToggle.jsx
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303565
> feat(AdaptiveCards): add the missing ac prop types to each component

- src/components/generic/OptionsList/OptionsList.jsx
- src/components/generic/OptionsList/OptionsList.scss
- src/components/hooks/index.js
- src/components/hooks/useElementPosition.js
PR link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302175
> feat(OptionsList): limit the height of dropdown options

- src/components/adaptive-cards/ActionSubmit/ActionSubmit.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302809
> fix(AdaptiveCard): fix return value of the validate() function

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/Component/Component.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303091
> fix(AdaptiveCards): process AdaptiveCard $schema and version properties

- src/components/generic/OptionsList/Option.jsx
- src/components/generic/Select/Select.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303306
> fix(OptionsList): prevent scroll on page when navigating with arrow keys between dropdown items

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304119
> fix(InputChoiceSet): add getError function

- src/adapters/ActivitiesJSONAdapter.js
- src/adapters/ActivitiesJSONAdapter.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303611
> feat(ActivitiesJsonAdapter): implement postActivity() method

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputToggle/InputToggle.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292453
> feat(AdaptiveCardsInputToggle): implement Input.Toggle component

- jest.setup.js
- src/components/adaptive-cards/Action/Action.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/FactSet/FactSet.jsx
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/adaptive-cards/InputNumber/InputNumber.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/InputTime/InputTime.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
- src/components/adaptive-cards/TextRun/TextRun.jsx
- src/components/adaptive-cards/util.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-296983
> feat(AdaptiveCard): implement date and time formatting

- src/components/generic/InputField/InputField.scss
- src/components/inputs/DateInput/DateInput.jsx
- src/components/inputs/DateInput/DateInput.scss
- src/components/inputs/DateInput/DateInput.stories.js
- src/components/inputs/DateInput/__snapshots__/DateInput.stories.storyshot
- src/components/inputs/_inputs.scss
- src/components/inputs/index.js
- src/themes/dark.scss
- src/themes/light.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289935
> feat(DateInput): implement DateInput component

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
- src/components/adaptive-cards/TextBlock/TextBlock.scss
- src/components/adaptive-cards/_adaptive-cards.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-303817
> feat(AdaptiveCardsTextBlock): implement maxLines property

- package-lock.json
- package.json
- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Markdown/Markdown.jsx
- src/components/adaptive-cards/Markdown/Markdown.scss
- src/components/adaptive-cards/TextBlock/TextBlock.jsx
- src/components/adaptive-cards/_adaptive-cards.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292840
> feat(AdaptiveCardsTextBlock): add markdown support

- src/adapters/ActivitiesJSONAdapter.js
- src/adapters/ActivitiesJSONAdapter.test.js
- src/components/WebexActivity/WebexActivity.jsx
- src/components/hooks/useAdaptiveCard.js
- src/data/activities.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304127
> refactor(ActivitiesJsonAdapter): refactor activity.card and useAdaptiveCard hook

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/data/activities.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304883
> docs(storybook): fix typo for radio button

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304502
> feat(AdaptiveCard): remove input error when user changes value

- src/components/inputs/TimeInput/TimeInput.jsx
- src/components/inputs/TimeInput/TimeInput.scss
- src/components/inputs/TimeInput/TimeInput.stories.js
- src/components/inputs/TimeInput/__snapshots__/TimeInput.stories.storyshot
- src/components/inputs/_inputs.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289949
> feat(TimeInput): implement TimeInput component

- src/components/adaptive-cards/ActionOpenURL/ActionOpenUrl.jsx
- src/components/adaptive-cards/ActionSubmit/ActionSubmit.jsx
- src/components/adaptive-cards/ActionToggleVisibility/ActionToggleVisibility.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Component/Component.scss
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/TextRun/TextRun.jsx
- src/components/adaptive-cards/hooks/useAction.js
- src/components/adaptive-cards/hooks/useActionOpenUrl.js
- src/components/adaptive-cards/hooks/useActionSubmit.js
- src/components/adaptive-cards/hooks/useActionToggleVisibility.js
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304091
> feat(AdaptiveCards): implement selectAction property

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304504
> feat(AdaptiveCard): display a default error message for required and regex if missing

- .eslintrc.json
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/Image/Image.jsx
- src/components/adaptive-cards/TextRun/TextRun.jsx
- src/components/hoc/withAdapter.jsx
- src/components/hoc/withMeeting.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305171
> style(components): disable "react/jsx-props-no-spreading" eslint rule

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/hooks/useActionSubmit.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304503
> feat(AdaptiveCard): show values on invalid submit only on storybook

- .storybook/preview-head.html
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304815
> fix(preview-head): set overflow property on root container

- .eslintrc.json
- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/Column/Column.jsx
- src/components/adaptive-cards/ColumnSet/ColumnSet.jsx
- src/components/adaptive-cards/Container/Container.jsx
- src/components/adaptive-cards/FactSet/FactSet.jsx
- src/components/adaptive-cards/ImageSet/ImageSet.jsx
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/adaptive-cards/RichTextBlock/RichTextBlock.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305228
> style(components): disable "react/no-array-index-key" eslint rule

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305264
> fix(AdaptiveCard): remove height property from adaptive card

- src/components/generic/OptionsList/OptionsList.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304625
> fix(OptionsList): prevent horizontal scrollbar

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
- src/components/inputs/Label/Label.jsx
- src/components/inputs/Label/Label.scss
- src/components/inputs/Textbox/Textbox.jsx
- src/components/inputs/Textbox/Textbox.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304507
> feat(Textbox): allow custom height in multiline input text

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304516
> feat(AdaptiveCard): add round border for adaptive card

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/WebexMeetingControl.jsx
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingControlBar/__snapshots__/WebexMeetingControlBar.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305929
> fix(WebexMeetingControl): send pressed prop only if the control is of the toggle type

- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304608
> fix(InputField): change color variables for InputField

- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305971
> fix(themes): add color-scheme property to change theme for native components

- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories.js
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304512
> feat(AdaptiveCard): display fallback text if the version of the adaptive card is not supported

- rollup.config.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-306443
> build(rollup): fix build

- src/components/generic/InputField/InputField.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-305964
> fix(InputField): eliminate extra outline for input field

- src/components/WebexMeetingGuestAuthentication/WebexMeetingGuestAuthentication.jsx
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/WebexMeetingHostAuthentication.jsx
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/generic/InputField/InputField.jsx
- src/components/inputs/PasswordInput/PasswordInput.jsx
- src/components/inputs/index.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304178
> feat(inputs): create PasswordInput component

- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-307261
> fix(themes): change some color variables for dropdown

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/generic/Modal/Modal.jsx
- src/components/inputs/Dropdown/Dropdown.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-307259
> fix(Dropdown):  collapse dropdown when pressing esc key on the keyboard

- src/components/generic/OptionsList/OptionsList.jsx
- src/components/hooks/useElementPosition.js
- src/components/inputs/Dropdown/Dropdown.jsx
- src/components/inputs/Dropdown/Dropdown.scss
- src/components/inputs/Dropdown/__snapshots__/Dropdown.stories.storyshot
- src/components/inputs/Dropdown/__snapshots__/Select.stories.storyshot
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-304508
> fix(Dropdown): keep options inside the viewport and hide them on outside scroll

- src/components/generic/Button/Button.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-307314
> fix(Button): prevent vertical shrinking

- src/components/adaptive-cards/ActionSubmit/ActionSubmit.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/Actions.stories.js
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/hooks/useActionSubmit.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292809
> feat(AdaptiveCardsActionExecute): make Action.Execute an alias of Action.Submit

- src/components/generic/InputField/InputField.jsx
- src/components/generic/InputField/InputField.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-307769
> refactor(InputField): improve input field UI states

- src/components/inputs/Dropdown/Dropdown.scss
- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-307263
> fix(Dropdown): fix background color in focus state

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/generic/InputField/InputField.jsx
- src/components/inputs/Dropdown/Dropdown.jsx
- src/components/inputs/Label/Label.jsx
- src/components/inputs/Label/Label.scss
- src/components/inputs/Textbox/Textbox.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-307765
> fix(components): link label and input control in a more accessible way

- src/themes/dark.scss
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-310305
> feat(themes): add new classname to theme files for integration in web-client

- src/components/WebexActivity/WebexActivity.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-311004
> fix(WebexActivity): make WebexActivity work if an adapter isn't yet present on the context

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/Inputs.stories.js
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/adaptive-cards/Component/Component.jsx
- src/components/adaptive-cards/InputText/InputText.jsx
- src/components/adaptive-cards/InputText/InputText.scss
- src/components/adaptive-cards/_adaptive-cards.scss
- src/components/inputs/Textbox/Textbox.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-311496
> feat(AdaptiveCardsInputText): implement inlineAction property

- src/components/generic/InputField/InputField.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-308974
> fix(InputField): set fixed height

- package-lock.json
- package.json
- src/adapters/RoomsJSONAdapter.js
- src/adapters/RoomsJSONAdapter.test.js
- src/components/hooks/useActivityScroll.js
- src/components/hooks/useActivityStream.js
- src/components/hooks/useOverflowActivities.js
Rooms adapter method names updated to match interface.
~~Requires package-lock.json to be updated once https://github.com/webex/component-adapter-interfaces/pull/82 is merged~~
[SPARK-302946](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-302946)
> refactor(RoomsAdapter): update rooms adapter method names

- src/components/adaptive-cards/util.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313000
> fix(AdaptiveCardsUtil): change the replaceAll method for compatibility with older browsers

- src/components/WebexActivity/WebexActivity.jsx
- src/components/WebexActivity/WebexActivity.scss
- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexActivityStream/__snapshots__/WebexActivityStream.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-312252
> fix(WebexActivity): set white-space just for message text

- src/components/generic/InputField/InputField.scss
- src/components/inputs/Textbox/Textbox.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-308996
> fix(components): show box-shadow on input on iOS

- src/components/index.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313806
> fix(contexts): export AdapterContext and MeetingContext

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/inputs/NumberInput/NumberInput.jsx
- src/components/inputs/TextInput/TextInput.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-313818
> fix(inputs): add aria-label on clear button

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/adaptive-cards/InputChoiceSet/InputChoiceSet.jsx
- src/components/inputs/Checkbox/Checkbox.jsx
- src/components/inputs/Checkbox/Checkbox.scss
- src/components/inputs/CheckboxSet/CheckboxSet.jsx
- src/components/inputs/RadioButton/RadioButton.jsx
- src/components/inputs/RadioButton/RadioButton.scss
- src/components/inputs/RadioSet/RadioSet.jsx
- src/components/inputs/Toggle/Toggle.jsx
- src/components/inputs/index.js
- src/themes/light.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-311802
> feat(components): improve accessibility for Checkbox, Radio button and Toggle components

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/inputs/NumberInput/NumberInput.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-314793
> fix(NumberInput): add aria-label on increase and decrease buttons

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/generic/InputField/InputField.jsx
- src/components/inputs/CheckboxSet/CheckboxSet.jsx
- src/components/inputs/Dropdown/Dropdown.jsx
- src/components/inputs/RadioSet/RadioSet.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-309217
> feat(inputs): add aria-errormessage and aria-invalid on inputs

- src/components/WebexAdaptiveCard/WebexAdaptiveCard.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-315247
> feat(WebexAdaptiveCard): add onSubmit prop to notify when submit starts and ends

- src/components/WebexSettings/Tabs.jsx
- src/components/generic/OptionsList/Option.jsx
- src/components/inputs/Checkbox/Checkbox.jsx
- src/components/inputs/Dropdown/Dropdown.jsx
- src/components/inputs/RadioButton/RadioButton.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-312821
> fix(components): stop bubbling for processed a11y arrow key events

- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexMeetingGuestAuthentication/__snapshots__/WebexMeetingGuestAuthentication.stories.storyshot
- src/components/WebexMeetingHostAuthentication/__snapshots__/WebexMeetingHostAuthentication.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/generic/Button/Button.jsx
- src/components/generic/Button/Button.scss
- src/components/icons/_icons.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-316090
> fix(icons): correct the color of icon for a button in disabled state

- package.json
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-316238
> build(package): add main field in package.json

- src/components/WebexActivity/__snapshots__/WebexActivity.stories.storyshot
- src/components/WebexAdaptiveCard/WebexAdaptiveCard.jsx
- src/components/WebexAdaptiveCard/WebexAdaptiveCard.scss
- src/components/_components.scss
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.scss
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Actions.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/CardElements.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Containers.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.stories/__snapshots__/Inputs.stories.storyshot
- src/components/adaptive-cards/AdaptiveCard/__snapshots__/AdaptiveCard.stories.storyshot
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-316615
> feat(WebexAdaptiveCard): add submit status message

- package.json
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-317527
we need this to make jest work on web client
> build(package): set umd bundle as main entry

- src/components/WebexAdaptiveCard/WebexAdaptiveCard.jsx
- src/components/WebexAdaptiveCards/WebexAdaptiveCards.jsx
- src/components/adaptive-cards/ActionSet/ActionSet.jsx
- src/components/adaptive-cards/AdaptiveCard/AdaptiveCard.jsx
- src/components/adaptive-cards/hooks/useActionOpenUrl.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-317869
> feat(AdaptiveCards): notify when a show card or open url action was performed

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter/controls/MuteVideoControl.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-309635
> fix(MeetingsJsonAdapter): prevent camera usage on iOS 15.1 due to iOS bug

- src/components/inputs/DateInput/DateInput.scss
- src/components/inputs/TimeInput/TimeInput.scss
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-318443
> fix(DateInput,TimeInput): adjust native browser controls icon position

- src/components/SignIn/SignIn.jsx
- src/components/hooks/index.js
- src/components/hooks/useMetrics.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-311577
Emit Operational Metrics from Sign In components
> feat(SignIn): emit operational metrics

- src/components/WebexSearchPeople/WebexSearchPeople.scss
story link-https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-329280
This change provides the css fix in user avatar that should be round in shape and also provides fix in the webex search alignment dropdown
> fix(WebexCreateSpace): css fix webex search avatar

- src/components/WebexCreateSpace/WebexCreateSpace.jsx
- src/components/WebexCreateSpace/WebexCreateSpace.stories.js
- src/components/WebexSearchPeople/WebexSearchPeople.jsx
- src/components/WebexSearchPeople/WebexSearchPeople.stories.js
- src/util.js
1. add a debounce method on the onChange event when user starts searching people.
2. Add a classname prop to the create space component
> feat(WebexSearchPeople): add debounce method on onChange event

- src/components/WebexCreateSpace/WebexCreateSpace.scss
- src/components/WebexSearchPeople/WebexSearchPeople.scss
1. Extra space on top of the search bar is fixed.
2. Text alignment of the heading and added people fixed
> fix(WebexCreateSpace):remove extra space on top of search field and text alignment issue fixes

- src/components/SignIn/SignIn.jsx
- src/components/SignIn/__snapshots__/SignIn.stories.storyshot
feat(SignIn): update classname
> feat(SignIn): update classname

- src/components/WebexCreateSpace/README.md
Readme file added in the create space component
> docs(WebexCreateSpace): add readme.md  file

- src/components/WebexCreateSpace/WebexCreateSpace.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-326862
> feat(WebexCreateSpace): emit operational metrics in create space component

- package-lock.json
- package.json
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.stories.storyshot
- src/storyshots.test.js
Fixes the issue where user is not able to drag the remote video/participants while screen is being shared.
**Issue** - [SPARK-409279](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-409279)
https://github.com/webex/components/assets/16598065/2c5338a8-3745-4cf2-b3d5-0a72d4266ab1
> fix(WebexRemoteMedia): make remote video draggable

- .github/workflows/npm-storybook-release.yml
> fix: update the release script to use workflow

- src/components/hooks/useMeetingDestination.js
> fix(meeting): do not call leave if not joined - release

- src/components/WebexInMeeting/WebexInMeeting.jsx
Minor change to trigger semantic release to publish new version
> fix(release): minor change to trigger semantic release to publish new version
