webex/components

- .circleci/config.yml
So I installed our components library and noticed that our `dist` directory is not downloaded into the directory. in our previous PR we had to separate our `build` job from `release` job in case of blocking the release if the build job had failed. after that change, I noticed that the `dist` directory is not included to the `release` job, which makes sense. We did not add the `dist` directory anywhere to be included to the next job which is a release job. So I decided to use `workspace` to persist the data (node_modules from the `install` job + dist directory from the `build` job) between the jobs. This actually turned out to be a better performant process, since we are not unarchiving the whole repo for each job anymore. and only apply the `node_modules` - 63 MB layer to all jobs and …
> CircleCI Cache Fix

- package-lock.json
- package.json
- rollup.config.js
Moving RxJS as a peer dependency instead of bundling it with the component code. An issue of incompatible RxJS libraries was found when trying to use the component bundle with `create-react-app` + RxJS.
> RXJS peer dependency

- package-lock.json
- package.json
- src/components/WebexLocalMedia/README.md
- src/components/WebexLocalMedia/WebexLocalMedia.js
- src/components/WebexLocalMedia/WebexLocalMedia.scss
- src/components/WebexLocalMedia/WebexLocalMedia.stories.js
- src/components/WebexLocalMedia/WebexLocalMedia.test.js
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.test.js.snap
- src/components/hooks/index.js
- src/components/hooks/useElementDimensions.js
- src/data/meetings.json
This a version that relies on the size on the container based on the [Resize Observable API](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver).
Replaces https://github.com/webex/components/pull/81, which is based on media queries (which look at the window, not the container).
> Webex Local Media styles based on container width

- src/components/WebexInMeeting/WebexInMeeting.js
- src/components/WebexInMeeting/WebexInMeeting.scss
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.test.js.snap
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.js
- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexInterstitialMeeting/__snapshots__/WebexInterstitialMeeting.test.js.snap
- src/components/WebexLocalMedia/WebexLocalMedia.js
- src/components/WebexLocalMedia/WebexLocalMedia.scss
- src/components/WebexLocalMedia/WebexLocalMedia.test.js
- src/components/WebexLocalMedia/__snapshots__/WebexLocalMedia.test.js.snap
- src/components/WebexMeeting/WebexMeeting.js
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/__snapshots__/WebexMeeting.test.js.snap
- src/components/WebexMeetingControl/WebexMeetingControls.js
- src/components/WebexMeetingControl/WebexMeetingControls.scss
- src/components/WebexMeetingControl/WebexMeetingControls.test.js
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControls.test.js.snap
- src/components/WebexMeetingInfo/WebexMeetingInfo.js
- src/components/WebexMeetingInfo/WebexMeetingInfo.test.js
- src/components/WebexMeetingInfo/__snapshots__/WebexMeetingInfo.test.js.snap
- src/components/WebexRemoteMedia/WebexRemoteMedia.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.test.js
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.test.js.snap
After merging #93 we discovered some issues due to expectation of child component classnames.
This PR limits the styles for each component and creates new "container" elements that the parent component styles for layout of the child component only.
One example of the issue this fixes is the usage of the `WebexLocalMedia` component within the `WebexInMeeting` component. The in meeting component was attempting to position the local media component with the class name "remote-media" that comes from the child component. This causes an interdependency between the components and requires strings to be updated in multiple places.
> Container styling encapsulation

- .github/CODEOWNERS
Fixes incorrect CODEOWNERS file from https://github.com/webex/components/pull/96.
> build(codeowners): add all files under core team

- src/components/hooks/useParticipants.js
`useParticipants` hook makes a shallow copy the `members` array of a membership. Without sending a new object, React does not detect that there has been a change to the participant list.
Bug tracked by [SPARK-158264](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-158264)
> fix(hooks): cloned members before setting state

- src/components/WebexParticipantRoster/WebexParticipantRoster.js
It's a 1 liner PR to fix a bug that the dynamic components (generated from loops) should come with a key property.
JIRA:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-158618
> fix(roster): add key property to WebexParticipant

- README.md
- package-lock.json
- package.json
- rollup.config.js
- src/adapters/index.js
- src/components/WebexParticipant/WebexParticipant.jsx
- src/index.js
- src/index.umd.js
Momentum UI as peer dependency of UMD bundle. Momentum UI causes build issues with their Sass. It's pretty heavy too and found that there is an AMD package hosted in [unpkg](https://unpkg.com/browse/@momentum-ui/react).
Moving outside of our bundle for performance purposes, as it is also a x10 reduction in size for the components UMD bundle.
Momentum UI CSS is also moved to its own file (another x10 reduction in size).
Adding `unpkg` to `package.json` so Webex. Components can be hosted properly in [unpkg](https://unpkg.com).
Added back JSON adapter as part of the distribution, as it can be useful for quick testing.
> Momentum UI as peer dependency of UMD bundle

- src/components/hooks/useStream.js
The previous useRef hook was not called when the reference got mounted and never properly attached the stream to the dom element.
> fix(useStream): add support for empty ref

- .circleci/config.yml
Git didn't like it, even though CircleCI recommended it ¯\\\_(ツ)\_/¯.
I blame [CircleCI poor instructions](https://support.circleci.com/hc/en-us/articles/360018860473-How-to-push-a-commit-back-to-the-same-repository-as-part-of-the-CircleCI-job) 😁
> ci: specify git config as local

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.stories.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexMeetingInfo/WebexMeetingInfo.stories.js
- src/components/WebexRemoteMedia/WebexRemoteMedia.stories.js
- src/components/hooks/useMeetingDestination.js
- src/data/meetings.js
Changing the flow when a user leaves a meeting. Instead of attempting to reset the meeting, we simply let the user know that they have left the meeting.
If they wish to rejoin the meeting, they can restart the meeting flow. This aligns with changes in the SDK where once a user leaves a meeting, a new meetingID is given, and simplifies the flow.
> Handle state when user leaves a meeting

- .circleci/config.yml
Release step fails because of changes committed in Storybook job.
> ci: fetch repository changes before releasing

- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/components/WebexRemoteMedia/WebexRemoteMedia.jsx
- src/components/WebexRemoteMedia/WebexRemoteMedia.scss
- src/components/WebexRemoteMedia/__snapshots__/WebexRemoteMedia.stories.storyshot
This changes the display style when there is remote video + screen share. Currently, the script is split 50%-50% which makes it hard to see the screen share. This updates the style so that video is shrunk and send to the top-right corner while screen share takes over the the full parent's (element) size.
> Remote Media Styles Fixes

- .circleci/config.yml
Checking before running Storybook does two things:
- Bring the CI branch with changes from release
- Adds github.com to ~/.ssh/known_host so we can push back changes to Github
> Checkout repository before running storybook step

- .circleci/config.yml
This allows for node_modules to be present when running this step
> ci: attach workspace before checkout in storybook step

- package.json
Missing the caret on the momentum-ui/react dependency, which is breaking a bump in Cisco Online Account Management Portal. Thank you!
> build(bump): allowing newest momentum ui for node bump

- .circleci/config.yml
I checked CircleCI's `checkout` command and it only fetches the remote branch but it doesn't integrate the changes on the workspace. Updating Storybook step to pull before committing.
Found after [this CI job failure](https://app.circleci.com/pipelines/github/webex/components/993/workflows/7fd74037-40e6-4aa1-b181-4ff488260d4c/jobs/2093)
> ci: integrate remote changes before building Storybook

- README.md
Encouraging use of the component Sass avoids an issue where Momentum styles page-level items
> docs(readme): use Momentum UI components for Sass

- src/components/WebexMember/WebexMember.jsx
- src/components/WebexMember/WebexMember.scss
- src/components/WebexMember/WebexMember.stories.js
- src/components/WebexMember/__snapshots__/WebexMember.stories.storyshot
- src/components/WebexMemberRoster/__snapshots__/WebexMemberRoster.stories.storyshot
Updated WebexMember to display the external user's organization name in WebexMemberRoster if the member is not from the same organization as the current user.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220418
> feat(WebexMember): display exernal user's organization

- src/adapters/MeetingsJSONAdapter.js
- src/components/WebexInMeeting/__snapshots__/WebexInMeeting.stories.storyshot
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
- src/data/meetings.js
Separate remote share logic from local share. Remote share should take its value only from the meeting object
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227221
> refactor(WebexJsonAdaptor): separate localShare from remoteShare

- .circleci/config.yml
Storybook previews run on all branches for all jobs. Previews should not get generated for `master`
> ci: don't run Storybook previews on master

- src/components/hooks/useMeetingDestination.js
Make the useMeetingDestination hook work even if an adapter is not yet present on the context
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-233400
> fix(useMeetingDestination): work even if an adapter is not yet present on the context

- src/components/WebexMeeting/README.md
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeeting/WebexMeeting.scss
- src/components/WebexMeeting/WebexMeeting.stories.js
- src/components/WebexMeeting/__snapshots__/WebexMeeting.stories.storyshot
In order to display the meeting controls under both the meeting and roster components in the WebexMeeting widget, the meeting component is refactored in the sense of no longer rendering the controls in this place.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-233369
Depends on: #239
> feat(WebexMeeting): remove WebexMeetingControlBar from WebexMeeting component

- package-lock.json
- package.json
This PR is about updating the component-adapter-interfaces version to v1.18.0﻿.
> fix(package): update component adapter interfaces to v1.18.0﻿

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter.test.js
- src/adapters/MeetingsJSONAdapter/controls/DisabledJoinControl.js
- src/adapters/MeetingsJSONAdapter/controls/DisabledMuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/JoinControl.js
- src/adapters/MeetingsJSONAdapter/controls/JoinWithoutCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/JoinWithoutMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/LeaveControl.js
- src/adapters/MeetingsJSONAdapter/controls/MeetingControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteAudioControl.js
- src/adapters/MeetingsJSONAdapter/controls/MuteVideoControl.js
- src/adapters/MeetingsJSONAdapter/controls/RosterControl.js
- src/adapters/MeetingsJSONAdapter/controls/SettingsControl.js
- src/adapters/MeetingsJSONAdapter/controls/ShareControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/index.js
For better encapsulation and code that is easier to maintain, the control functions (display & action) have been moved from the main meetings adapter file to individual files that are easier to read and maintain (eg. src/MeetingsSDKAdapter/JoinControl.js).
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-242542
> refactor(MeetingsJsonAdapter): implement each JSON adapter meeting control in its own file

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchMicrophoneControl.js
This PR is fixing the bug where the display name of the media devices is not shown while permission is not granted by adding a default display name.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-245970
> fix(MeetingsJsonAdapter): ignore media devices without an id and use device id as fallback label

- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter/controls/ProceedWithoutCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/ProceedWithoutMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/index.js
- src/components/WebexMediaAccess/WebexMediaAccess.jsx
- src/components/WebexMediaAccess/__snapshots__/WebexMediaAccess.stories.storyshot
Refactor joinWithoutCameraControl and joinWithoutMicrophoneControl to proceedWithoutCamera/Microphone, as the user will not be joined in the meeting, it just consents that accepts to proceed without camera or microphone during the meeting
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-245167
> refactor(MeetingsJsonAdapter): add "proceed without device" controls

- src/components/WebexMember/WebexMember.jsx
This PR is about displaying a loading state beside participants avatars while their names are being fetched.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-245911
> fix(WebexMember): add loading state while names are being fetched

- src/components/hooks/useMeetingDestination.js
This PR is about doing the properly cleanup when a meeting widget unmounts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-247816
> feat(UseMeetingDestination): remove media and leave meeting when component unmounts from dom

- src/components/WebexInterstitialMeeting/WebexInterstitialMeeting.scss
- src/components/WebexMeetingInfo/WebexMeetingInfo.scss
This PR fixes the bug where meeting title is placed right on top of the video in interstitial meeting.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-266336
> fix(WebexMeetingInfo): add margin bottom to meeting title

- src/components/generic/Modal/Modal.jsx
Fixes
Closing modal icon should be 16x16
> fix(Modal): set size for the "close" icon in the settings window

- src/components/WebexMeetingControl/WebexMeetingControl.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-269357
> fix(WebexMeetingControl): add a correct property name for font family to webex control styling file

- rollup.config.js
Rollup is not honoring babel configuration, this fixes it
> fix(rollup): use babelrc

- src/components/WebexMeeting/README.md
- src/components/WebexMeeting/WebexMeeting.jsx
- src/components/WebexMeetingControlBar/WebexMeetingControlBar.jsx
In this PR it was added the controls prop in order to be able to pass a custom list of controls to WebexMeetingControlBar component coming from above. 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-270964
> feat(WebexMeeting): add controls prop to meeting component

- .eslintrc.json
- src/adapters/MeetingsJSONAdapter.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchCameraControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchMicrophoneControl.js
- src/adapters/MeetingsJSONAdapter/controls/SwitchSpeakerControl.js
- src/components/WebexAudioSettings/WebexAudioSettings.jsx
- src/components/WebexMeetingControl/__snapshots__/WebexMeetingControl.stories.storyshot
- src/components/WebexSettings/__snapshots__/WebexSettings.stories.storyshot
- src/components/WebexVideoSettings/WebexVideoSettings.jsx
- src/components/generic/Select/Select.jsx
- src/components/generic/Select/Select.scss
- src/data/meetings.js
- src/themes/dark.scss
- src/themes/light.scss
Detects the specific media error when a media stream can not be obtained from the browser. Disables the switch camera & microphone dropdowns when there are no available devices on the system, or they exist but are disabled. Still displays the "no media" message in settings when the user has not granted access (denied, dismissed or just ignored the prompt).
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-290114
> feat(WebexSettings): disable dropdowns when no devices are available

- src/components/hooks/useActivity.js
- src/components/hooks/useAdaptiveCard.js
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-309971
> fix(hooks): make useActivity and useAdaptiveCard work if an adapter isn't yet present on the context

- src/components/generic/Tooltip/Tooltip.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-316551
This PR removes button tooltips altogether because we could not find a fix for the tooltip misalignment on mobile. That issue is most likely caused by the fact that scroll position is affected by the address bar that hides on scroll down (only with HTTPS, not HTTP). If someone can correctly position tooltips on mobile, the mobile tooltips can be re-enabled
https://stackoverflow.com/questions/50914207/position-fixed-on-chrome-mobile-causing-issues-when-scrolling
> fix(Tooltip): don't display tooltip if on devices with touch

- .storybook/main.js
- package-lock.json
- package.json
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-540929 
Storybook build failure happened due to incompatibility between Webpack 4 and node 20. Installed the builder-webpack5 version 6.5.16 and used it as a builder for the storybook.
> fix(tooling): upgraded webpack version to be used for storybook

- package-lock.json
- package.json
This PR upgrades the version of React in components to 18.3.1 as 17.0.2 has been out of support for a couple of years now and the older react version is causing problems while developers try to build new applications. This activity is being done as part of [SPARK-551578](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-551578)
I've only changed the react, react-dom and any testing library to the same version. Left the remaining dependencies as they are.
> feat(react): update react version to 18.3.1

- src/components/WebexMember/WebexMember.jsx
Issue:- The user is trying to enter the name according to their wish but whatever the name entered by the user unfortunately it not going to display on the sample app when you click to see in the participants list means it taking the system default name so for this issue the following changes are done
This PR updates the logic for displaying the member's name in the `WebexMember` component. If the `member.name` is unavailable, it will fall back to the `displayName`. This ensures more consistent name handling within the component.
https://github.com/user-attachments/assets/1c4ad4c7-ea95-4dfc-b98d-74b4b9e48356
when you are not providing the name that means whenever the name field is empty and not provides anything then the display name will system default name …
> fix(webexMember): updated member name handling
